web: gunicorn config.wsgi:application --bind 0.0.0.0:${PORT:-8000} --workers ${WEB_CONCURRENCY:-4} --threads 2
worker: celery -A config.celery_app worker -l info
beat: celery -A config.celery_app beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
